theme: jekyll-theme-minimal
title: "Anonymous\nAutonomous"
description: "An interactive robotic art installation currently in development at the University of Michigan, 
transforming empty office chairs to behave like driverless cars."
pages: 
  - title: Materials
  - title: Getting Started
  - title: About Us
